[config]
model = "gpt-4o-mini"
model_turbo = "gpt-4o-mini"  
language = "ko"
verbosity_level = 0

[pr_reviewer]
auto_review = true
num_code_suggestions = 3
inline_code_comments = true
enable_help_text = false
persistent_comment = true

# 코드컨벤션 파일 참조 및 핵심 지침
extra_instructions = """
반드시 한국어로 작성해주세요.

코드컨벤션은 .github/code-conventions.yml 파일을 참조하여 검토해주세요.

## 핵심 검토 항목:
1. **FSD 아키텍처**: features/[domain]/ vs shared/ 분리 확인
2. **네이밍**: kebab-case(파일) / PascalCase(컴포넌트) / camelCase(변수)  
3. **API 구조**: {domain}API.{method} 패턴, @/api에서 import
4. **React**: Props interface + 비구조화 할당, useCallback/useMemo 적절한 사용
5. **타입 안정성**: TypeScript 오류, Generic 활용
6. **성능**: 불필요한 리렌더링, key prop 배열 인덱스 금지

우선순위: 버그 → 타입 오류 → 아키텍처 위반 → 성능 → 가독성
"""

[pr_description]
publish_description = true
add_original_user_description = true
use_bullet_points = true

[pr_code_suggestions]
auto_improve = true
num_code_suggestions = 2
commitable_code_suggestions = true

extra_instructions = """
한국어로 체인지로그 작성:

### Added
- 새로운 기능

### Changed
- API 구조 변경
- 기존 기능 개선

### Fixed
- 버그 수정

### Removed
- 제거된 기능
"""

[github]
publish_inline_comments = true
publish_review_comments = true
add_pr_commands_text = true