module.exports = {
  extends: ['@commitlint/config-conventional'],
  rules: {
    'type-enum': [
      2,
      'always',
      [
        'feat',
        'fix',
        'refactor',
        'docs',
        'test',
        'chore',
        'style',
        'delete',
        'move',
        'update',
        'ci',
        'build',
        'hotfix',
      ],
    ],
    'subject-case': [0],
    'header-max-length': [0],
  },

  ignores: [
    (message) => message.startsWith('Merge pull request'),
    (message) => message.startsWith('Merge branch'),
    (message) => message.includes('Merge remote-tracking branch'),
    (message) => message.startsWith('UF-'),
    (message) => message.startsWith('[UF-'),
    (message) => /^UF-\d+/.test(message),
    (message) => /^\[UF-\d+\]/.test(message),
    (message) => message.startsWith('Revert'),
    (message) => message.startsWith('Initial commit'),
    (message) => message.startsWith('hotfix:'),
    (message) => message.startsWith('🔥'),
    (message) => /^hotfix\/.+/.test(message),
  ],
};
