export const IMAGE_PATHS = {
  AL_SAD: '/images/alien-sad.png',
  AL_HAPPY: '/images/alien-happy.png',
  AL_ONBOARDING: '/images/alien-onboarding.svg',
  AL_SELL: '/images/alien-sell.png',
  AL_REPORTED: '/images/alien-sad-reported.png',
  AL_BULK_PURCHASE: '/images/alien-bulk.png',
  AL_COMPLETE: '/images/alien-serious-reported.svg',
  AL_SOWHAT: '/images/alien-sowhat.svg',
  AL_SUCCESS: '/images/alien-success.svg',
  AL_FAIL: '/images/alien-fail.svg',
  AL_PW_WRONG: '/images/alien-wrong.svg',
  AL_EXCHANGE: '/images/exchange/exchange_alien.svg',
  STONE: '/images/exchange/stone.svg',
  NEXT_BTN_ONBOARDING: '/images/next-btn.png',
  FIRE_BTN_ONBOARDING: '/images/fire-btn.png',
  BG_LOGIN: '/images/background-login.png',
  BG_BASIC: '/images/background-basic.png',
  BLACKHOLE_REAL: '/images/blackhole-real.png',
  NOT_FOUND: '/images/not-found.png',
  WARNING: '/images/warning.png',
  MAIN: '/images/main.png',
  PACKAGE_A: '/images/zet-1.png',
  PACKAGE_B: '/images/zet-2.png',
  PACKAGE_C: '/images/zet-3.png',
  PACKAGE_D: '/images/zet-4.png',
  PACKAGE_E: '/images/zet-5.png',
  PLANET_1: '/images/main/planet1.svg',
  PLANET_2: '/images/main/planet2.svg',
  PLANET_3: '/images/main/planet3.svg',
  PLANET_4: '/images/main/planet4.svg',
  PLANET_5: '/images/main/planet5.svg',
  SATELLITE_1: '/images/satellite1.svg',
  SATELLITE_2: '/images/satellite2.svg',
  SATELLITE_3: '/images/satellite3.svg',
  SATELLITE_4: '/images/satellite4.svg',
  SATELLITE_5: '/images/satellite5.svg',
  KAKAO_LOGIN_BUTTON: '/images/kakao-login-button.png',
  UFO_LOGIN: '/images/ufo-login.png',
  PAYMENT_CHECK: '/images/check-primary.svg',
  AVATAR: '/images/avatar.svg',
  QR: '/images/QR.png',
  IC: '/images/IC.png',
  UFO_LOGO: '/images/ufo-logo.svg',
  PURCHASE_COIN: '/images/purchase-coin.svg',
  DATA_CUBE: '/images/data-cube.svg',
  PURCHASE_COMPLETED: '/images/purchase-completed.svg',
  BADGES_LOCKED: '/icons/badges/locked.svg',
  MY_PLANET: '/images/main/myplanet.svg',
  MY_PLANET_HALF: '/images/myplanet-half.svg',
  RECEIPT: '/images/receipt.svg',
  CLOUD: '/images/cloud.svg',
  WINDOW: '/images/onboarding/window.svg',
  WINDOW_BORDER: '/images/onboarding/window-border.svg',
  WINDOW_MASK: '/images/onboarding/window-mask.svg',
  WINDOW_BOTTOM: '/images/onboarding/window-bottom.svg',
} as const;

export const BADGE_ICONS: Record<string, string> = {};

[1, 2, 3, 4].forEach((lv) => {
  [1, 2, 3].forEach((i) => {
    BADGE_ICONS[`lv${lv}-${i}`] = `/icons/badges/lv${lv}-${i}.svg`;
  });
});
