export const IMAGE_PATHS = {
  AL_SAD: '/images/alien-sad.png',
  AL_HAPPY: '/images/alien-happy.png',
  AL_ONBOARDING: '/images/alien-onboarding.png',
  AL_SELL: '/images/alien-sell.png',
  AL_REPORTED: '/images/alien-sad-reported.png',
  AL_BULK_PURCHASE: '/images/alien-bulk.png',
  AL_COMPLETE: '/images/alien-serious-reported.png',
  AL_SOWHAT: '/images/alien-sowhat.svg',
  AL_PW_WRONG: '/images/alien-wrong.svg',
  NEXT_BTN_ONBOARDING: '/images/next-btn.png',
  FIRE_BTN_ONBOARDING: '/images/fire-btn.png',
  BG_ONBOARDING: '/images/background-onboarding.png',
  BG_LOGIN: '/images/background-login.png',
  BG_BASIC: '/images/background-basic.png',
  BLACKHOLE_REAL: '/images/blackhole-real.png',
  NOT_FOUND: '/images/not-found.png',
  WARNING: '/images/warning.png',
  MAIN: '/images/main.png',

  PACKAGE_A: '/images/package-a.png',
  PACKAGE_B: '/images/package-b.png',
  PACKAGE_C: '/images/package-c.png',
  PACKAGE_D: '/images/package-d.png',
  PACKAGE_E: '/images/package-e.png',

  KAKAO_LOGIN_BUTTON: '/images/kakao-login-button.png',
  UFO_LOGIN: '/images/ufo-login.png',
} as const;
