#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

BRANCH=$(git rev-parse --abbrev-ref HEAD)
if [[ $BRANCH == hotfix/* ]] || [[ $BRANCH == "develop" ]] || [[ $BRANCH == "main" ]]; then
  echo "Special branch detected ($BRANCH), skipping commitlint"
  exit 0
fi

npx --no -- commitlint --edit "$1"